# Generated by Django 4.2.5 on 2023-10-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                ("email", models.EmailField(max_length=150, verbose_name="email")),
                ("subject", models.CharField(max_length=150, verbose_name="subject")),
                ("message", models.TextField(verbose_name="message")),
            ],
        ),
    ]
