# Generated by Django 4.2.5 on 2023-10-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactmodel",
            options={"verbose_name": "message", "verbose_name_plural": "messages"},
        ),
        migrations.AddField(
            model_name="contactmodel",
            name="is_read_by_admin",
            field=models.BooleanField(default=False, verbose_name="Is Read By Admin"),
        ),
    ]
