# Generated by Django 4.2.5 on 2023-10-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostCategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=300, verbose_name="title"
                    ),
                ),
                (
                    "url_title",
                    models.CharField(
                        db_index=True, max_length=300, verbose_name="name in url"
                    ),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.AddField(
            model_name="postmodel",
            name="category",
            field=models.ManyToManyField(
                related_name="post_categories",
                to="blog_app.postcategorymodel",
                verbose_name="categories",
            ),
        ),
    ]
