# Generated by Django 4.2.5 on 2023-10-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0002_postcategorymodel_postmodel_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="postmodel",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/products",
                verbose_name="image post",
            ),
        ),
    ]
