# Generated by Django 4.2.5 on 2023-10-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0003_postmodel_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmodel",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/posts",
                verbose_name="image post",
            ),
        ),
    ]
