# Generated by Django 4.2.5 on 2023-10-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0005_alter_postmodel_image_alter_postmodel_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="name")),
                ("message", models.TextField(verbose_name="comment")),
            ],
            options={
                "verbose_name": "commnet",
                "verbose_name_plural": "comments",
            },
        ),
    ]
