# Generated by Django 4.2.5 on 2023-10-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0006_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="writed_date",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="writed date"
            ),
        ),
    ]
