# Generated by Django 4.2.5 on 2023-10-12 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0007_comment_writed_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="postmodel",
            name="comments",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog_app.comment",
                verbose_name="comments",
            ),
        ),
    ]
